import { z } from 'zod'
import {
  FAILURE_STATUSES,
  FAILURE_TARGETS,
  LOAD_TYPES,
  REP_MODES,
  SET_COMPONENT_TYPES,
  SET_ROLES,
  STRUCTURE_TYPES,
} from '../../domain/enums/training'

const nullable_string = z.string().nullable()
const nullable_number = z.number().nullable()
const nullable_integer = z.number().int().nullable()

const mutable = {
  id: z.string().min(1),
  created_at: z.string().min(1),
  updated_at: z.string().min(1),
  deleted_at: nullable_string,
  revision: z.number().int().min(1),
  device_id: z.string().min(1),
  source_kind: z.enum([
    'user',
    'programme_import',
    'historical_import',
    'restore',
    'sync',
  ]),
  source_id: nullable_string,
}

const mutable_schema = z.object(mutable).passthrough()

function mutable_record(shape: Record<string, z.ZodTypeAny>) {
  return z.object({ ...mutable, ...shape }).passthrough()
}

const schemas: Record<string, z.ZodTypeAny> = {
  schema_meta: z.object({
    key: z.literal('main'),
    db_schema_version: z.number().int().min(1),
    data_contract_version: z.string().min(1),
    created_at: z.string().min(1),
    updated_at: z.string().min(1),
  }).passthrough(),
  migration_history: z.object({
    version: z.number().int().min(1),
    app_version: z.string(),
    migration_name: z.string(),
    migration_checksum: z.string(),
    applied_at: z.string(),
    result: z.enum(['success', 'failed']),
  }).passthrough(),
  devices: z.object({
    id: z.string().min(1),
    display_name: z.string(),
    platform: z.string(),
    first_seen_at: z.string(),
    last_seen_at: z.string(),
  }).passthrough(),
  settings: z.object({
    key: z.string().min(1),
    scope: z.enum(['global', 'device']),
    value_json: z.unknown(),
    updated_at: z.string(),
    device_id: nullable_string,
  }).passthrough(),

  exercises: mutable_record({
    canonical_name: z.string().min(1),
    short_name: nullable_string,
    category: nullable_string,
    equipment: nullable_string,
    machine_brand: nullable_string.optional(),
    machine_model: nullable_string.optional(),
    origin_gym_profile_id: nullable_string.optional(),
    default_load_type: z.enum(LOAD_TYPES),
    rep_mode_default: z.enum(REP_MODES),
    archived_at: nullable_string,
    notes: nullable_string,
  }),
  exercise_aliases: mutable_record({
    exercise_id: z.string().min(1),
    source_exercise_id: z.string().min(1),
    alias: z.string().min(1),
    normalized_alias: z.string().min(1),
  }),
  gym_profiles: mutable_record({
    name: z.string().min(1),
    short_name: z.string().min(1),
    kind: z.enum(['home', 'previous', 'travel']),
    is_inventory_complete: z.boolean(),
    notes: nullable_string,
  }),
  gym_exercise_availability: mutable_record({
    gym_profile_id: z.string().min(1),
    exercise_id: z.string().min(1),
    available: z.boolean(),
    equipment_label: nullable_string,
    machine_brand: nullable_string.optional(),
    machine_model: nullable_string.optional(),
    notes: nullable_string,
  }),
  muscles: z.object({
    id: z.string().min(1),
    name: z.string().min(1),
    region: nullable_string,
  }).passthrough(),
  exercise_muscles: z.object({
    id: z.string().min(1),
    exercise_id: z.string().min(1),
    muscle_id: z.string().min(1),
    role: z.enum(['primary', 'secondary', 'stabilizer']),
    allocation_weight: nullable_number,
  }).passthrough(),

  programme_blocks: mutable_record({
    name: z.string().min(1),
    block_type: z.enum(['mesocycle', 'microcycle', 'custom']),
    start_date_local: nullable_string,
    end_date_local: nullable_string,
    status: z.enum(['draft', 'active', 'completed', 'archived']),
    goal: nullable_string,
    notes: nullable_string,
  }),
  workout_templates: mutable_record({
    programme_block_id: nullable_string,
    name: z.string().min(1),
    day_label: nullable_string,
    template_family_id: z.string().min(1),
    version_number: z.number().int().min(1),
    status: z.enum(['draft', 'active', 'retired']),
    notes: nullable_string,
  }),
  template_exercises: mutable_record({
    workout_template_id: z.string().min(1),
    exercise_id: z.string().min(1),
    planned_order: z.number().int().min(1),
    rotation_group_key: nullable_string,
    rotation_position: nullable_integer,
    target_sets: z.number().int().min(1),
    target_rep_min: nullable_integer,
    target_rep_max: nullable_integer,
    rest_seconds: nullable_integer,
    tempo: nullable_string,
    technique_cue: nullable_string,
    notes: nullable_string,
  }),
  template_sets: mutable_record({
    template_exercise_id: z.string().min(1),
    set_number: z.number().int().min(1),
    set_role: z.enum(SET_ROLES),
    structure_type: z.enum(STRUCTURE_TYPES),
    target_rep_min: nullable_integer,
    target_rep_max: nullable_integer,
    target_duration_seconds: nullable_integer,
    target_load_kg: nullable_number,
    target_load_type: z.enum(LOAD_TYPES),
    failure_target: z.enum(FAILURE_TARGETS),
    notes: nullable_string,
  }),
  template_set_components: mutable_record({
    template_set_id: z.string().min(1),
    sequence: z.number().int().min(1),
    component_type: z.enum(SET_COMPONENT_TYPES),
    target_load_kg: nullable_number,
    load_relation: z.enum([
      'absolute',
      'same_as_primary',
      'percentage_of_primary',
      'unknown',
    ]),
    target_load_percent: nullable_number,
    target_rep_min: nullable_integer,
    target_rep_max: nullable_integer,
    target_duration_seconds: nullable_integer,
    failure_target: z.enum(FAILURE_TARGETS),
    notes: nullable_string,
  }),

  programmed_sessions: mutable_record({
    programme_block_id: nullable_string,
    workout_template_id: nullable_string,
    scheduled_date_local: nullable_string,
    name_snapshot: z.string().min(1),
    status: z.enum(['planned', 'started', 'completed', 'skipped', 'cancelled']),
    notes: nullable_string,
  }),
  programmed_session_exercises: mutable_record({
    programmed_session_id: z.string().min(1),
    exercise_id: z.string().min(1),
    exercise_name_snapshot: z.string().min(1),
    planned_order: z.number().int().min(1),
    rotation_group_key: nullable_string,
    rotation_position: nullable_integer,
    target_sets: nullable_integer,
    target_rep_min: nullable_integer,
    target_rep_max: nullable_integer,
    rest_seconds: nullable_integer,
    tempo: nullable_string,
    technique_cue: nullable_string,
    notes: nullable_string,
  }),
  programmed_session_sets: mutable_record({
    programmed_session_exercise_id: z.string().min(1),
    set_number: z.number().int().min(1),
    set_role: z.enum(SET_ROLES),
    structure_type: z.enum(STRUCTURE_TYPES),
    target_rep_min: nullable_integer,
    target_rep_max: nullable_integer,
    target_duration_seconds: nullable_integer,
    target_load_kg: nullable_number,
    target_load_type: z.enum(LOAD_TYPES),
    failure_target: z.enum(FAILURE_TARGETS),
    notes: nullable_string,
  }),
  programmed_set_components: mutable_record({
    programmed_session_set_id: z.string().min(1),
    sequence: z.number().int().min(1),
    component_type: z.enum(SET_COMPONENT_TYPES),
    target_load_kg: nullable_number,
    load_relation: z.enum([
      'absolute',
      'same_as_primary',
      'percentage_of_primary',
      'unknown',
    ]),
    target_load_percent: nullable_number,
    target_rep_min: nullable_integer,
    target_rep_max: nullable_integer,
    target_duration_seconds: nullable_integer,
    failure_target: z.enum(FAILURE_TARGETS),
    notes: nullable_string,
  }),

  completed_sessions: mutable_record({
    gym_profile_id: nullable_string.optional(),
    gym_name_snapshot: nullable_string.optional(),
    programmed_session_id: nullable_string,
    programme_block_id: nullable_string,
    workout_template_id_snapshot: nullable_string,
    legacy_workout_id: nullable_string,
    session_name: z.string().min(1),
    session_date_local: z.string().min(1),
    timezone: nullable_string,
    status: z.enum(['in_progress', 'completed', 'abandoned']),
    started_at: nullable_string,
    completed_at: nullable_string,
    source_start_text: nullable_string,
    source_finish_text: nullable_string,
    duration_seconds: nullable_integer,
    notes: nullable_string,
  }),
  readiness_entries: mutable_record({
    completed_session_id: z.string().min(1),
    bodyweight_kg: nullable_number,
    sleep_duration_minutes: nullable_integer,
    sleep_score: nullable_number,
    energy_pre: nullable_number,
    motivation_pre: nullable_number,
    soreness_score: nullable_number,
    soreness_notes: nullable_string,
    muscle_recovery: z.array(z.object({
      muscle: z.string().min(1),
      status: z.enum(['fresh', 'mild_soreness', 'sore', 'performance_affected']),
      source_session_id: z.string().min(1),
      source_session_date_local: z.string().min(1),
    })).optional(),
    joint_issue_present: z.boolean().nullable(),
    joint_issue_notes: nullable_string,
    pre_workout_nutrition: nullable_string,
    intra_workout_nutrition: nullable_string,
    intra_hydration_ml: nullable_number,
    post_workout_intake: nullable_string,
    session_fatigue: nullable_number,
    breathlessness: nullable_number,
    energy_stability: nullable_number,
    notes: nullable_string,
  }),
  session_exercises: mutable_record({
    completed_session_id: z.string().min(1),
    programmed_session_exercise_id: nullable_string,
    exercise_id: z.string().min(1),
    exercise_name_snapshot: z.string().min(1),
    planned_order: nullable_integer,
    actual_order: z.number().int().min(1),
    rotation_group_key: nullable_string,
    rotation_position: nullable_integer,
    target_sets: nullable_integer,
    target_rep_min: nullable_integer,
    target_rep_max: nullable_integer,
    rest_seconds: nullable_integer,
    tempo: nullable_string,
    technique_cue: nullable_string,
    programme_notes: nullable_string,
    started_at: nullable_string,
    completed_at: nullable_string,
    notes: nullable_string,
  }),
  sets: mutable_record({
    completed_session_id: z.string().min(1),
    session_exercise_id: z.string().min(1),
    exercise_id: z.string().min(1),
    exercise_order_snapshot: z.number().int().min(1),
    set_number: z.number().int().min(1),
    set_role: z.enum(SET_ROLES),
    structure_type: z.enum(STRUCTURE_TYPES),
    load_kg: nullable_number,
    load_type: z.enum(LOAD_TYPES),
    rep_mode: z.enum(REP_MODES),
    reps_as_recorded: nullable_string,
    primary_reps_completed: nullable_integer,
    left_reps_completed: nullable_integer,
    right_reps_completed: nullable_integer,
    completed_reps: nullable_integer,
    partial_reps: nullable_integer,
    duration_seconds: nullable_integer,
    failure_status: z.enum(FAILURE_STATUSES),
    left_failure_status: z.enum(FAILURE_STATUSES).nullable(),
    right_failure_status: z.enum(FAILURE_STATUSES).nullable(),
    actual_rest_seconds: nullable_integer,
    set_load_kg_reps: nullable_number,
    set_load_method: nullable_string,
    notes: nullable_string,
    completed_at: nullable_string,
    source_record_key: nullable_string,
  }),
  set_components: mutable_record({
    set_id: z.string().min(1),
    sequence: z.number().int().min(1),
    component_type: z.enum(SET_COMPONENT_TYPES),
    load_kg: nullable_number,
    load_type: z.enum(LOAD_TYPES).nullable(),
    reps_completed_full: nullable_integer,
    reps_partial: nullable_integer,
    duration_seconds: nullable_integer,
    failure_status: z.enum(FAILURE_STATUSES),
    counts_toward_comparable_tonnage: z.boolean(),
    notes: nullable_string,
  }),
  exercise_metrics: mutable_record({
    session_exercise_id: z.string().min(1),
    rpe: nullable_number,
    pump: nullable_number,
    form: nullable_number,
    where_felt_text: nullable_string,
    where_felt_tags: z.array(z.string()),
    legacy_tension: nullable_number,
    legacy_mmc: nullable_number,
    notes: nullable_string,
  }),
  coaching_notes: mutable_record({
    scope_type: z.enum(['programme', 'session', 'session_exercise', 'set', 'exercise']),
    scope_id: z.string().min(1),
    author_type: z.enum(['user', 'coach', 'import']),
    note: z.string(),
    tags: z.array(z.string()),
  }),

  import_batches: z.object({
    id: z.string().min(1),
    importer_type: z.string(),
    importer_version: z.string(),
    file_name: z.string(),
    file_sha256: z.string(),
    file_size_bytes: z.number().int().min(0),
    started_at: z.string(),
    completed_at: nullable_string,
    status: z.enum(['previewed', 'committed', 'failed', 'cancelled']),
    expected_sessions: nullable_integer,
    detected_sessions: nullable_integer,
    expected_exercises: nullable_integer,
    detected_exercises: nullable_integer,
    expected_sets: nullable_integer,
    detected_sets: nullable_integer,
    summary_json: z.unknown().nullable(),
  }).passthrough(),
  import_records: z.object({
    id: z.string().min(1),
    import_batch_id: z.string().min(1),
    source_sheet: z.string(),
    source_row_number: z.number().int().min(0),
    source_record_key: z.string().min(1),
    source_row_sha256: z.string(),
    entity_type: z.string(),
    entity_id: z.string(),
    raw_json: z.unknown(),
    data_status: nullable_string,
    source_text: nullable_string,
    imported_at: z.string(),
  }).passthrough(),
  import_issues: z.object({
    id: z.string().min(1),
    import_batch_id: z.string().min(1),
    severity: z.enum(['info', 'warning', 'error']),
    code: z.string(),
    source_sheet: nullable_string,
    source_row_number: nullable_integer,
    source_record_key: nullable_string,
    message: z.string(),
    raw_json: z.unknown().nullable(),
    resolution_status: z.enum(['open', 'resolved', 'ignored']),
    resolved_at: nullable_string,
  }).passthrough(),
  audit_events: z.object({
    id: z.string().min(1),
    entity_type: z.string().min(1),
    entity_id: z.string().min(1),
    action: z.enum([
      'create',
      'update',
      'soft_delete',
      'restore',
      'import',
      'restore_backup',
      'sync_apply',
    ]),
    before_json: z.unknown().nullable(),
    after_json: z.unknown().nullable(),
    reason: nullable_string,
    device_id: z.string().min(1),
    created_at: z.string(),
  }).passthrough(),
  sync_outbox: z.object({
    id: z.string().min(1),
    entity_type: z.string().min(1),
    entity_id: z.string().min(1),
    operation: z.enum(['upsert', 'delete']),
    revision: z.number().int().min(1),
    payload_json: z.unknown(),
    created_at: z.string(),
    attempt_count: z.number().int().min(0),
    last_attempt_at: nullable_string,
    synced_at: nullable_string,
  }).passthrough(),
  sync_state: z.object({
    provider: z.string().min(1),
    remote_user_id: nullable_string,
    pull_cursor: nullable_string,
    last_pull_at: nullable_string,
    last_push_at: nullable_string,
    status: z.enum(['disconnected', 'idle', 'syncing', 'error']),
    error: nullable_string,
  }).passthrough(),
  synced_settings: mutable_record({
    key: z.string().min(1),
    scope: z.literal('global'),
    value_json: z.unknown(),
  }),
}

export function validate_backup_record(
  table_name: string,
  record: Record<string, unknown>,
  record_number: number,
): void {
  const schema = schemas[table_name] ?? mutable_schema
  const result = schema.safeParse(record)
  if (result.success) return

  const first = result.error.issues[0]
  const path = first?.path.length ? `.${first.path.join('.')}` : ''
  throw new Error(
    `Backup table ${table_name} record ${record_number}${path} is invalid: ${first?.message ?? 'schema validation failed'}.`,
  )
}
